pytorch/helion

pyproject.toml
While trying to build helion on my setup noticed three problems
1) LICENSE file is misspent
2) `license-files` is no longer supported under `[project]` with PEP621 needs to move under setuptools
3) license now needs to be specified text or file
=> Fix license file for PEP 621

.pyre_configuration
This PR attempts to make Pyre capable of checking using either installed `torch` from site packages, or if it is available a `torch` coming from a repository at `../pytorch`, relative to the current `helion` repository.
-----------
The first diff improves our options for making a local pytorch repo work, because it eliminates the rigid assumption that we'll find `torch` in the site-packages directory (otherwise, Pyre will crash complaining about an invalid search path entry).
It's also generally simpler, and eliminates other potential consequences of trying to enumerate the site pachage entries; this is the go-to mode I would generally use for Pyre.
Tested by setting up a virtualenv, making sure `pyre check` works on trunk, and seeing that I get a clean result after this config change. …
=> Use search-strategy: all for all site packages in pyre config

helion/__init__.py, helion/_logging/__init__.py, helion/_logging/_internal.py, helion/runtime/kernel.py, test/test_logging.py
* #28
* __->__ #26
Usage:
```
HELION_LOGS=+helion.runtime.kernel python test.py
```
will run test.py with helion.runtime.kernel logs enabled at logging.DEBUG level
=> Add HELION_LOGS

examples/softmax.py, helion/_compiler/compile_environment.py, helion/_compiler/device_function.py, helion/_compiler/device_ir.py, helion/_compiler/generate_ast.py, helion/_compiler/host_function.py, helion/_compiler/indexing_strategy.py, helion/_compiler/inductor_lowering.py, helion/_compiler/reduction_strategy.py, helion/_compiler/roll_reduction.py, helion/_compiler/tile_dispatch.py, helion/_compiler/tile_index_proxy.py, helion/_compiler/tile_strategy.py, helion/_compiler/type_propagation.py, helion/_compiler/variable_origin.py, helion/autotuner/config_spec.py, helion/exc.py, helion/language/__init__.py, helion/language/_tracing_ops.py, helion/language/creation_ops.py, helion/language/loops.py, pyproject.toml, test/test_examples.py, test/test_loops.py, test/test_matmul.py, test/test_reductions.py
This change makes the two pass softmax @drisspg was trying to implement possible, with some new syntax for pre-registering block sizes:
```python
@helion.kernel(config={"block_sizes": [1, 128]})
def softmax_two_pass(x: torch.Tensor) -> torch.Tensor:
m, n = x.size()
out = torch.empty_like(x)
block_size_m = hl.register_block_size(m)
block_size_n = hl.register_block_size(n)
for tile_m in hl.tile(m, block_size=block_size_m):
mi = hl.full([tile_m, 1], float("-inf"), dtype=torch.float32)
di = hl.zeros([tile_m, block_size_n], dtype=torch.float32)
for tile_n in hl.tile(n, block_size=block_size_n):
values = x[tile_m, tile_n]
local_amax = torch.amax(values, dim=1, keepdim=True)
mi_next = torch.maximum(mi, local_amax)
di = di * torch.exp(mi - mi_next) + torch.exp(values - mi_next)
mi = mi_next
for …
```
=> Add hl.register_block_size and explicit tile sizes

.github/workflows/lint.yml, .github/workflows/test.yml, lint.sh
This allows us to `pip install pyre-check` rather than building from source by using a newer ubuntu image.
It also fixed a conflict between pyre and click 8.2 by downgrading click.
=> Update lint github workflow

.pyre_configuration
On local development, I have the PyTorch nightly pip install'ed into the `../pytorch-nightly` folder for easier file access. Would like to add this search path to Pyre config as well so that I can run lint check locally.
=> Add ../pytorch-nightly to Pyre optional_search_path

helion/_compat.py, helion/_compiler/output_header.py, helion/runtime/kernel.py, test/test_matmul.py
Running `examples/matmul.py` on latest Triton gives the following error:
```
$ python examples/matmul.py 
[0s] Starting DifferentialEvolutionSearch with population=40, generations=20, crossover_rate=0.8
Traceback (most recent call last):
File "/home/willfeng/local/helion_yf225/examples/matmul.py", line 41, in <module>
check(1024, 1024, 1024)
~~~~~^^^^^^^^^^^^^^^^^^
File "/home/willfeng/local/helion_yf225/examples/matmul.py", line 31, in check
result = matmul(x, y)
File "/home/willfeng/local/helion_yf225/helion/runtime/kernel.py", line 188, in __call__
return self.bind(args)(*args)
~~~~~~~~~~~~~~~^^^^^^^
File "/home/willfeng/local/helion_yf225/helion/runtime/kernel.py", line 383, in __call__
self.autotune(args)
~~~~~~~~~~~~~^^^^^^
File …
```
=> Fix TensorDescriptor handling in _find_device

helion/runtime/settings.py
Added in https://github.com/pytorch-labs/helion/pull/9, `use_default_config` is very helpful when we care about the lowering part but not the performance part of the Helion kernel compilation workflow.
It's common to want to run the examples in `examples/` folder to quickly check if the lowering part is working, and with the `HELION_USE_DEFAULT_CONFIG` env var introduced in this PR, we can easily do so without needing to go into the example file to manually add `use_default_config=True`.
=> Add HELION_USE_DEFAULT_CONFIG env var to force use default config

helion/_compiler/variable_origin.py
Currently, `examples/add.py` fails with the following error:
```
$ python examples/add.py 
[0s] Starting DifferentialEvolutionSearch with population=40, generations=20, crossover_rate=0.8
Traceback (most recent call last):
File "/home/willfeng/local/helion/helion/_compiler/ast_extension.py", line 218, in visit
return visitor(node)
File "/home/willfeng/local/helion/helion/_compiler/generate_ast.py", line 174, in visit_For
codegen_call_with_graph(
~~~~~~~~~~~~~~~~~~~~~~~^
self,
^^^^^
self.host_fn.device_ir.get_root(self.device_function.config),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[],
^^^
)
^
File "/home/willfeng/local/helion/helion/_compiler/inductor_lowering.py", line 711, in codegen_call_with_graph
return GraphInterpreter(gm, cg).run(*new_args) …
```
=> Make BlockSizeOrigin host_str return 1 for block_size=1 case

helion/_compiler/variable_origin.py
Same as https://github.com/pytorch-labs/helion/pull/38. I accidentally used the github merge button where I should have used `@pytorchbot merge` instead.
* #39
* __->__ #40
=> [2nd try] Make BlockSizeOrigin host_str return 1 for block_size=1 case

examples/matmul.py
Following the lines in the `matmul` kernel:
https://github.com/pytorch-labs/helion/blob/96253e7faf936dfcdf7c2484e561a5c5e30a7b02/examples/matmul.py#L12-L13
I believe x should be of `[m, k]` shape and y should be of `[k, n]` shape, so updating the `check()` function to use the same notation.
* __->__ #47
=> Minor fix on the matmul example dim notation

examples/attention.py, examples/softmax.py, helion/_compiler/compile_environment.py, helion/_compiler/indexing_strategy.py, helion/_compiler/inductor_lowering.py, helion/_compiler/output_header.py, helion/_compiler/roll_reduction.py, helion/autotuner/config_spec.py, helion/language/_tracing_ops.py, helion/language/loops.py, pyproject.toml, test/test_examples.py
Still a bunch of issues that need fixing:
1) The generated code is slow.  I think this is because we are using `[1, N, M]` tiles rather than `[N, M]` tiles and Triton generates bad code for 3D tiles.  Need to implement a "drop size==1 dims" pass.
2) It looks like we are hardcoding `sm_scale` and `head_dim` in the generated code.  I think this is because of the call to `math.sqrt`, but need to look into it.
3) We have some unnecessary masking for the reductions (and missing masking for the dot if shapes are non-multiples).  Need to polish the masking logic.
=> Add attention example and fix some bugs

helion/_compiler/device_ir.py, test/test_loops.py
@yf225 this should fix your issue
=> Fix bug where non-tensor variables are not exposed to inner loops

helion/_compiler/device_ir.py, helion/_compiler/indexing_strategy.py, helion/language/__init__.py, helion/language/_decorators.py, helion/language/memory_ops.py, pyproject.toml, test/test_atomic_add.py
Stacked PRs:
* __->__#63
--- --- ---
Prototyping an hl.atomic opp
I have been playing around with a few different variants different variants
```Py
hl.store(dy, tile_i, local_dy_grad, reduction_op="add")
```
I kinda of think that have the reduction op be semantic on store makes the most since we can map to: https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#data-movement-and-conversion-instructions-cp-reduce-async-bulk-tensor
I think we need this atomic op to back scatter_add w/ the function mode if we dont add directly to store
```Py
@helion.kernel(config=helion.Config(block_sizes=[32, 32]))
def mul_relu_block_back_kernel(
x: torch.Tensor, y: torch.Tensor, dz: torch.Tensor
) -> Tuple[Tensor, Tensor]:
m, n = x.shape
dx = torch.empty_like(x)
dy = torch.empty_like(y)
for …
```
=> Prototyping an hl.atomic opp

.github/workflows/test.yml, test/test_closures.py, test/test_examples.py
Yep, now we support `python -m unittest test/test_closures.py` on top of `pytest test/test_closures.py`.
=> [test] Touch test/__init__.py to support more testing workflows

helion/_compiler/type_propagation.py
Stacked PRs:
* __->__#84
--- --- ---
=> Don't re-wrap exceptions in exc.TorchOpTracingError

pyproject.toml, requirements.txt
Stacked PRs:
* #94
* #93
* __->__#95
--- --- ---
CI is failing with:
```
File ".../triton/_filecheck.py", line 6, in <module>
from filecheck.options import Options
ModuleNotFoundError: No module named 'filecheck'
```
=> Add filecheck dependency

helion/runtime/kernel.py, helion/runtime/settings.py
Stacked PRs:
* #94
* __->__#93
* #95
--- --- ---
=> Add env HELION_PRINT_OUTPUT_CODE=1

test/test_examples.py
Stacked PRs:
* #122
* __->__#121
--- --- ---
=> Skip test_moe_matmul_ogs on older cards

examples/moe_matmul_ogs.py, test/test_examples.py
The `if num_tokens != 0:` check is essential for the correctness of the kernel, but the check triggers Triton internal error on fbcode. So skipping the MoE unit test on fbcode only for now.
=> Re-enable unit test for moe_matmul_ogs example; skip in fbcode

README.md, examples/attention.py, examples/embedding.py, examples/jagged_dense_add.py, examples/long_sum.py, examples/template_via_closure.py, helion/_compiler/compile_environment.py, helion/_compiler/tile_dispatch.py, helion/_compiler/tile_strategy.py, helion/_compiler/type_propagation.py, helion/autotuner/config_generation.py, helion/autotuner/config_spec.py, helion/language/loops.py, helion/runtime/config.py, test/test_autotuner.py, test/test_broadcasting.py, test/test_control_flow.py, test/test_examples.py, test/test_generate_ast.py, test/test_logging.py, test/test_loops.py, test/test_matmul.py, test/test_specialize.py
Stacked PRs:
* #132
* #131
* #130
* #129
* #128
* __->__#127
* #126
--- --- ---
This removes the prior nested config structure where you would have:
block_sizes=[[8, 8], 8] for nested loops, and
block_sizes=[64, 8] for a flattened loop.
Instead, you would now have:
block_sizes=[8, 8, 8], flatten_loops=[False] for nested loops, and
block_sizes=[8, 8, 8] flatten_loops=[True] for a flattened loop
This makes config structures more predictable and easier to work with.
=> [BC breaking] Simplify block size configs

helion/_compiler/type_propagation.py, helion/exc.py
Stacked PRs:
* #132
* __->__#131
* #130
--- --- ---
=> Make helion.exc.TensorOperationInWrapper not fire on non-torch ops

examples/matmul_layernorm.py, helion/_compiler/compile_environment.py, helion/_compiler/device_ir.py, helion/_compiler/inductor_lowering.py, helion/_compiler/inductor_lowering_extra.py, helion/_compiler/roll_reduction.py, helion/_compiler/type_propagation.py, helion/language/__init__.py, helion/language/loops.py, helion/runtime/kernel.py, test/test_examples.py, test/test_misc.py
As titled. Things that are worthy to note:
1. Add `hl.register_reduction_dim()` API.
2. Adding handling `var_mean` (a reduction) returning a tuple of two nodes (or for ops to return multiple nodes in general).
3. Since Welford reduction is currently not supported in Helion yet, I changed the variance calculation to always use the "two-step variance" algorithm by patching the Inductor lowering of `var_mean` op. Once Welford reduction is supported, we can remove that patch and switch back to use Inductor `var_mean_helper_()`. At the same time I think the patching mechanism is useful in the development phase where Helion doesn't support specific Inductor lowerings yet.
=> [Ready for review] Add hl.register_reduction_dim(); add support for matmul+layernorm example

test/test_control_flow.py
Stacked PRs:
* #141
* __->__#142
--- --- ---
This test was failing:
https://github.com/pytorch-labs/helion/actions/runs/15520524821/job/43693128974?pr=141
It looks like noise:
```
Mismatched elements: 1 / 512 (0.2%)
Greatest absolute difference: 1.0371208190917969e-05 at index (65,) (up to 1e-05 allowed)
Greatest relative difference: 4.182314296485856e-05 at index (65,) (up to 1.3e-06 allowed)
```
=> Increase atol/rtol for test_error_in_non_taken_branch

examples/attention.py
Stacked PRs:
* __->__#146
--- --- ---
More fair comparison
```Shell
❯ python examples/attention.py
Helion time: 0.2387ms, flex time: 2.9446, torch time: 0.0719
❯ code examples/attention.py
❯ python examples/attention.py
Helion time: 0.2368ms, flex time: 0.0640, torch time: 0.0722
```
=> More fair comparison

helion/_compiler/device_ir.py, test/test_control_flow.py, test/test_examples.py
Closes https://github.com/pytorch-labs/helion/issues/153. This PR will hopefully fix the Triton internal error on RTX 3090 / 5070 Ti (the unit test skip is removed now) and also on fbcode (I will test it first before landing this PR).
=> Codegen `if tl.sum(one_elem_tensor):` instead of `if one_elem_tensor`

helion/_compiler/device_ir.py, test/test_atomic_add.py
Stacked PRs:
* #187
* __->__#180
--- --- ---
ghstack-source-id: fefa4f8e9d0a1ff27cdd1abdffba9e3d4e2319a4
Pull Request resolved: https://github.com/pytorch-labs/helion/pull/178
=> Fix visitCall in deviceIR. Always visit argument nodes

helion/_compiler/inductor_lowering.py, test/test_indexing.py
Stacked PRs:
* #188
* __->__#187
--- --- ---
=> Add lowering for Constant assignment

helion/language/__init__.py, helion/language/tile_ops.py, helion/language/tile_proxy.py, test/test_indexing.py
Stacked PRs:
* #189
* __->__#188
--- --- ---
=> Expose tile.id

helion/_compiler/type_propagation.py
in https://github.com/pytorch/pytorch/pull/154757I added a meta function for view, the following fail because python_dispatcher not enabled in general it should always be enabled when a pass is doing tracing through fake tensors.
=> enable_python_dispatcher() in propagate_types

helion/_compiler/device_ir.py, helion/language/_tracing_ops.py, test/test_examples.py, test/test_loops.py, test/test_masking.py, test/test_matmul.py, test/test_misc.py, test/test_register_tunable.py, test/test_type_propagation.py
* #213
* #212
* #211
* #210
* #209
* #208
* __->__#206
* #205
--- --- ---
Fix bug with renamed variable flowing into phi() node
Fixes #199
=> Fix bug with renamed variable flowing into phi() node

helion/_compiler/program_id.py, helion/_compiler/tile_strategy.py, helion/_compiler/type_propagation.py, helion/language/loops.py, test/test_grid.py
* #213
* #212
* __->__#211
* #210
* #209
* #208
* #206
* #205
--- --- ---
Add support for hl.grid(begin, end, step)
=> Add support for hl.grid(begin, end, step)

helion/_compiler/device_ir.py, helion/language/loops.py, test/test_errors.py, test/test_grid.py
* #213
* __->__#212
* #211
* #210
* #209
* #208
* #206
* #205
--- --- ---
Support range() loops (alias for hl.grid)
Fixes #207
=> Support range() loops (alias for hl.grid)

helion/_compiler/device_ir.py, helion/_compiler/tile_strategy.py
* __->__#213
* #212
* #211
* #210
* #209
* #208
* #206
* #205
--- --- ---
Move yz_grid disabling logic to ConfigSpec
This generates a smaller search space which is easier to autotune.
=> Move yz_grid disabling logic to ConfigSpec

helion/_compiler/device_ir.py, helion/_compiler/indexing_strategy.py, test/test_broadcasting.py, test/test_control_flow.py, test/test_examples.py, test/test_grid.py, test/test_masking.py, test/test_register_tunable.py
Stacked PRs:
* #189
* __->__#223
--- --- ---
=> x[i] returns scalar when i=scalar

.pyre_configuration, test/test_examples.py
* #230
* #229
* #228
* #227
* #226
* #225
* __->__#231
--- --- ---
Fix failing tests on main
=> Fix failing tests on main

examples/add.py, examples/attention.py, examples/bmm.py, examples/concatenate.py, examples/embedding.py, examples/jagged_dense_add.py, examples/long_sum.py, examples/matmul.py, examples/matmul_layernorm.py, examples/matmul_split_k.py, examples/moe_matmul_ogs.py, examples/softmax.py, examples/template_via_closure.py, helion/_testing.py, helion/runtime/kernel.py, test/test_examples.py, test/test_type_propagation.py
* #230
* #229
* #228
* #227
* #226
* __->__#225
* #231
--- --- ---
Refactor examples to use run_example helper
=> Refactor examples to use run_example helper

README.md, helion/_compiler/reduction_strategy.py, helion/_compiler/tile_strategy.py, helion/autotuner/config_spec.py, helion/language/loops.py, helion/runtime/config.py, test/test_autotuner.py, test/test_examples.py, test/test_grid.py, test/test_loops.py, test/test_masking.py, test/test_matmul.py, test/test_misc.py, test/test_reductions.py, test/test_register_tunable.py
* #232
* #230
* #229
* #228
* #227
* __->__#226
--- --- ---
Add tl.range loop_unroll_factor to autotuner
=> Add tl.range loop_unroll_factor to autotuner

README.md, helion/_compiler/tile_strategy.py, helion/autotuner/config_spec.py, helion/language/loops.py, helion/runtime/config.py, test/test_autotuner.py, test/test_loops.py
* #232
* #230
* __->__#229
* #228
* #227
* #226
--- --- ---
Add tl.range flatten to autotuner
=> Add tl.range flatten to autotuner

helion/_compiler/compile_environment.py, helion/_compiler/device_function.py, helion/_compiler/device_ir.py, helion/_compiler/generate_ast.py, helion/_compiler/helper_function.py, helion/_compiler/inductor_lowering.py, helion/exc.py, helion/language/__init__.py, helion/language/_decorators.py, helion/language/scan_ops.py, test/test_associative_scan.py
* #241
* #240
* __->__#239
* #238
--- --- ---
Add hl.associative_scan
=> Add hl.associative_scan

examples/rms_norm.py, test/test_examples.expected, test/test_examples.py
Stacked PRs:
* #257
* #256
* #253
* __->__#252
--- --- ---
- Implement RMS normalization kernel using helion
- Add PyTorch reference implementation
- Add unit test in test_examples.py with expected output
=> Add rms_norm example and test

helion/_testing.py, test/test_associative_scan.expected, test/test_atomic_add.expected, test/test_broadcasting.expected, test/test_closures.expected, test/test_constexpr.expected, test/test_control_flow.expected, test/test_generate_ast.expected, test/test_indexing.expected, test/test_reduce.expected, test/test_specialize.expected, test/test_type_propagation.expected, test/test_views.expected
* #254
* __->__#255
--- --- ---
Strip extra newlines from *.expected files
=> Strip extra newlines from *.expected files

examples/sum.py, test/test_examples.expected, test/test_examples.py
Stacked PRs:
* #257
* __->__#256
* #253
* #252
--- --- ---
- Add sum kernel that reduces 2D tensors along the last dimension
- Add unit test for sum kernel
=> Add sum example and test

benchmark/run.py, examples/sum.py
Stacked PRs:
* __->__#257
* #256
* #253
* #252
--- --- ---
- Add sum_tritonbench wrapper function that handles 1D input
- Add sum to KERNEL_MAPPINGS in benchmark/run.py
- Include kernel reset logic to ensure clean state before benchmarking
NOTE: tritonbench’s Triton kernel currently errors when the input size is large. Submitted a fix at https://github.com/pytorch-labs/tritonbench/pull/269.
=> [Benchmark] Add sum to TritonBench integration

benchmarks/run.py, examples/all_gather_matmul.py, examples/segment_reduction.py, helion/_compiler/ast_extension.py, helion/_compiler/ast_read_writes.py, helion/_compiler/inductor_lowering_extra.py, helion/_compiler/traceback_compat.py, helion/_compiler/type_printer.py, helion/autotuner/base_search.py, helion/runtime/__init__.py, helion/runtime/config.py, pyproject.toml
* #317
* #316
* __->__#315
* #314
* #313
--- --- ---
Enforce ANN/PGH lints
One thing we lost in the pyre => pyright switch is enforcing that
everything is typed (I had disabled ANN since the errors were rudundant
with pyre).
=> Enforce ANN/PGH lints

helion/_compiler/device_ir.py, test/test_examples.expected, test/test_loops.expected, test/test_loops.py
Stacked PRs:
* __->__#324
--- --- ---
Fixes issue where variables defined in outer loop scopes were not accessible in subsequent inner loops within the same outer loop iteration.
This pattern is common in multi-pass algorithms like layernorm.
=> Fix variable scoping in nested loops for multi-pass kernels

examples/cross_entropy.py, test/test_examples.expected, test/test_examples.py
Stacked PRs:
* #321
* __->__#320
* #325
--- --- ---
=> Add cross_entropy example and unit test

examples/fp8_attention.py, helion/_testing.py, test/test_examples.expected, test/test_examples.py
Stacked PRs:
* #319
* __->__#318
--- --- ---
=> Add fp8_attention example and unit test

benchmarks/run.py
Stacked PRs:
* __->__#319
* #318
--- --- ---
=> [Benchmark] Add fp8_attention to tritonbench integration

helion/_compiler/device_ir.py, test/test_misc.expected, test/test_misc.py
Stacked PRs:
* __->__#334
--- --- ---
Fixes #332
Previously it was erroring with
```
helion.exc.InternalError: RuntimeError: Tile(0) (139684109802224)is not
tracked with proxy for
<torch.fx.experimental.proxy_tensor.PythonKeyTracer object at
0x7f0abf06cc90>
```
=> Do not create a new variable for tile assignments since tiles are immutable

helion/_compiler/inductor_lowering.py, helion/_compiler/reduction_strategy.py, test/test_reductions.expected, test/test_reductions.py
* #361
* __->__#357
--- --- ---
Fix fp16 var_mean multi-output issue
Fixes #344
=> Fix fp16 var_mean multi-output issue

helion/_testing.py, helion/_utils.py, helion/autotuner/__init__.py, helion/autotuner/base_cache.py, helion/autotuner/local_cache.py, helion/runtime/config.py, helion/runtime/kernel.py, test/test_cache.py
Stacked PRs:
* __->__#336
--- --- ---
=> [RFC] Implement basic on disk caching

helion/autotuner/base_cache.py
Stacked PRs:
* __->__#395
--- --- ---
Fixes #392
=> Temporarily move triton_key import to inner function to unblock older torch versions

examples/matmul.py, examples/matmul_split_k.py, helion/language/loops.py, test/test_examples.expected, test/test_matmul.expected, test/test_type_propagation.expected
* #415
* #414
* #413
* #412
* __->__#411
--- --- ---
Fix non-tuple indexing warning
```
UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result
```
=> Fix non-tuple indexing warning

benchmarks/run.py
- `--k` is by default an abbreviation of `--kernel`, preventing `--kernel gemm --k 4096` from working. This PR fixes it.
- Add `--op` that aliases `--kernel`, for better tritonbench arg name matching.
=> [Benchmark] Fix arg parsing issue in tritonbench integration

test/test_associative_scan.py
These tests started failing after https://github.com/pytorch/pytorch/pull/159708 due to HOP starting to go through `__torch_function__`-based dispatch.
After @mlazos 's PR https://github.com/pytorch/pytorch/pull/159910 is landed into PyTorch nightly, I will re-enable these tests.
=> Skip associative_scan tests in ref eager mode

helion/_compiler/indexing_strategy.py, helion/_compiler/type_propagation.py, helion/_compiler/utils.py, test/test_indexing.py
Stacked PRs:
* __->__#426
* #425
* #424
--- --- ---
=> Fix strided slice support for static slices (e.g., buf[::2])

helion/_compiler/device_function.py, helion/runtime/__init__.py, test/test_associative_scan.expected, test/test_atomic_add.expected, test/test_broadcasting.expected, test/test_closures.expected, test/test_constexpr.expected, test/test_control_flow.expected, test/test_dot.expected, test/test_examples.expected, test/test_generate_ast.expected, test/test_grid.expected, test/test_indexing.expected, test/test_inline_asm_elementwise.expected, test/test_loops.expected, test/test_masking.expected, test/test_matmul.expected, test/test_misc.expected, test/test_persistent_kernels.expected, test/test_reduce.expected, test/test_reductions.expected, test/test_register_tunable.expected, test/test_signal_wait.expected, test/test_specialize.expected, test/test_stack_tensor.expected, test/test_unroll_tuples.expected, test/test_views.expected
* __->__#427
--- --- ---
Better fix for triton allocator error
Turns out the root cause of the prior issue was the addition of ContextVar, not needing it for non-TensorDescriptors.
=> Better fix for triton allocator error

test/test_associative_scan.py
https://github.com/pytorch/pytorch/pull/159910 is landed, we should be able to run them now.
=> Re-enable associative_scan tests in ref eager mode

benchmarks/run.py
The tritonbench runner in fbcode has a weird `pytorch.` path prefix and it's difficult to remove it due to existing usage within fbcode. So we add a try-catch to handle this in `benchmarks/run.py`.
=> [Benchmark] Add try-catch for tritonbench import path

benchmarks/README.md, benchmarks/run.py
This PR replaces all instances of `pytorch-labs` with `meta-pytorch` in this repository now that the `pytorch-labs` org has been renamed to `meta-pytorch`
- Replaced all occurrences of `pytorch-labs` with `meta-pytorch`
- Only modified files with extensions: .py, .md, .sh, .rst, .cpp, .h, .txt, .yml
- Skipped binary files and files larger than 1MB due to GitHub api payload limits in the script to cover all repos in this org. Will do a more manual second pass later to cover any larger files
This PR updates files that contained the target text.
Generated by automated script on 2025-08-12T20:58:24.763506+00:00Z
=> [EZ] Replace `pytorch-labs` with `meta-pytorch`

helion/_compiler/generate_ast.py
This PR addresses two main points:
1. Piping AST arguments into `._codegen`
2. When the host-side function returns a sequence-like output but is not `TileIndexType`, correctly fallback to using `api._codegen`
Side note, I’m not entirely sure how to handle default AST arguments. For now, I’m just using `ast_params.apply_defaults()`, but I’m unsure if that’s the best way.
=> [generate_ast] providing AST args, and fall back to `api._codegen` when output is a tuple

helion/_compiler/compile_environment.py, helion/_compiler/device_function.py, helion/_compiler/tile_dispatch.py, helion/_utils.py, helion/runtime/ref_mode.py, test/test_views.py
Previously, reshape operations with expressions containing block_size symbols (like tile_m.block_size * tile_n.block_size) would fail or generate incorrect code. This commit adds symbol analysis functions to identify and map block symbols to their runtime variables, enabling complex block_size arithmetic in reshape operations.
=> Support reshape with block_size expressions

helion/_compiler/device_ir.py, test/test_indexing.expected, test/test_indexing.py
With this PR, we are able to support slicing with multiples-of-block-size as slice length, by lowering the slice to `hl.arange` (Related PR: https://github.com/pytorch/helion/pull/509).
```python
indices_start = tile.begin * 2
indices_end = indices_start + tile.block_size * 2
out[indices_start:indices_end] = ones[indices_start:indices_end]
```
This is part of https://github.com/pytorch/helion/issues/508.
=> Lower symbolic slices to hl.arange

helion/_compiler/generate_ast.py, helion/_compiler/host_function.py, helion/_compiler/type_propagation.py, helion/_testing.py, helion/runtime/kernel.py, test/test_misc.expected, test/test_misc.py
Stacked PRs:
* __->__#514
--- --- ---
=> Add call function to triton output for easier repros

helion/_compiler/inductor_lowering.py, helion/language/matmul_ops.py, test/test_dot_requirements.py
* __->__#522
--- --- ---
Fix missing min block size for hl.dot
Fixes #467
=> Fix missing min block size for hl.dot

examples/jagged_mean.py, examples/moe_matmul_ogs.py, test/test_examples.expected, test/test_examples.py
Using dummy tensor to pass in int arg is not necessary.
=> Pass int arg instead of dummy tensor into example kernels

test/test_misc.py
Before the fix, they fail with:
```
____________________________________________________________ TestMisc.test_triton_repro_custom_static_shapes_True _____________________________________________________________
self = <test.test_misc.TestMisc testMethod=test_triton_repro_custom_static_shapes_True>, static_shapes = True
@skipIfRefEager("no code execution")
@parametrize("static_shapes", (True, False))
def test_triton_repro_custom(self, static_shapes):
@helion.kernel(static_shapes=static_shapes)
def kernel(t: torch.Tensor, i: int, s: str, b: bool, f: float) -> torch.Tensor:
out = torch.empty_like(t)
for tile in hl.tile(t.size()):
if b and len(s) > 2:
out[tile] = t[tile] + i + f
return out
a = torch.randn(16, 1, device=DEVICE)
bound_kernel = kernel.bind((a, 1, "foo", True, 1.2))
code = …
```
=> Fix local runs for test_triton_repro tests

helion/_compiler/device_ir.py, helion/_compiler/inductor_lowering.py, test/test_views.expected, test/test_views.py
Fixes https://github.com/pytorch/helion/issues/523.
=> Add torch.stack support

.github/workflows/benchmark.yml, .github/workflows/test.yml, benchmarks/run.py
Stacked PRs:
* __->__#544
--- --- ---
=> Create basic helion benchmark runner

helion/_testing.py, test/test_autotuner.py, test/test_cache.py, test/test_loops.py, test/test_misc.py
Local environments usually have `HELION_USE_DEFAULT_CONFIG=1` on by default to do development on non-autotuner features, and some local envs also have low available GPU memory.
This PR adds `use_default_config=False` explicitly to specific unit tests so that they still work even if `HELION_USE_DEFAULT_CONFIG=1` is set, and also skip specific unit tests when GPU VRAM is low.
=> Add `skipIfLowVRAM` or `use_default_config=False` to specific unit tests to enable local testing

helion/exc.py, helion/language/loops.py, test/test_ref_eager.py
Warns users when they specify block_size parameters to hl.tile() in interpret mode, since the block_size is ignored and full dimension size is always used in interpret mode.
Added a testcase to check that a warning is printed when block_size is specified in interpret mode.
Addresses issue: https://github.com/pytorch/helion/issues/466
=> Print warning if block_size is specified in interpret mode.

examples/layer_norm.py, test/test_examples.expected
layer_norm was failing accuracy check (e.g. https://github.com/pytorch/helion/actions/runs/17533111246/job/49792650005) due to hardcoded torch.float16 dtype in the Helion kernel. This PR fixes it.
=> [Benchmark] Fix layer_norm accuracy issue

helion/autotuner/differential_evolution.py
Stacked PRs:
* __->__#583
--- --- ---
currently we end up compiling the same kernel 4 times i think. 1
precompile and 1 cached compile during iter_candidates and another set
of these again in benchmark_flat.
=> Do not benchmark twice

helion/_testing.py
* #595
* __->__#592
--- --- ---
Fix tf32 warning
```
UserWarning: Please use the new API settings to control TF32 behavior, such as
▌torch.backends.cudnn.conv.fp32_precision = 'tf32' or torch.backends.cuda.matmul.fp32_precision = 'ieee'. Old settings, e.g,
▌torch.backends.cuda.matmul.allow_tf32 = True, torch.backends.cudnn.allow_tf32 = True, allowTF32CuDNN() and allowTF32CuBLAS()
▌will be deprecated after Pytorch 2.9.
```
=> Fix tf32 warning

examples/rms_norm.py, test/test_examples.expected, test/test_examples.py
Summary: We add the backward pass for rms_norm kernel
Differential Revision: D82359685
=> Add rms_norm backward kernels

benchmarks/run.py, examples/kl_div.py, test/test_examples.expected, test/test_examples.py
Stacked PRs:
* __->__#615
--- --- ---
=> [Benchmark] kl_div kernel and test

helion/autotuner/config_generation.py
Summary: We add block_size heuristics for autotune since it can have ValueError for tensors with large shape.
Differential Revision: D82742888
=> Fix ValueError: numel (2097152) exceeds triton maximum tensor numel (1048576)

.github/workflows/benchmark.yml
Currently tritonbench swallows all exceptions and proceeds to the next input shape, which makes legitimate exceptions hard to find in the log. With this PR, it will now exit the benchmark CI job on any exception.
=> [Easy][Benchmark CI] Exit job on any exception, for easier error catching

helion/autotuner/logger.py
We actually want the CUDA-context-crashing errors to bubble up and terminates the autotuning process, to be able to identify them more easily (and also the CUDA context is already crashed at that point so future CUDA launches won't be working anyways). This would help surface errors like https://github.com/pytorch/helion/issues/634.
=> Avoid skipping CUDA errors that crashes the CUDA context

test/test_autotuner.py
Seems to have similar accuracy issue as https://github.com/pytorch/helion/pull/648.
=> Skip test_autotune_random_seed_from_settings on rocm

helion/_compiler/indexing_strategy.py, test/test_tensor_descriptor.expected, test/test_tensor_descriptor.py
I've found 1x16 tile access to be the culprit for matmul "misaligned address" errors. This should fix the issue mentioned in https://github.com/pytorch/helion/pull/654#issuecomment-3325201565.
=> Fix misaligned address error for matmul

test/test_examples.py
Stacked PRs:
* __->__#666
--- --- ---
=> skip gather_gemv code check for B200 and fb_code

examples/rms_norm.py
This PR along with https://github.com/meta-pytorch/tritonbench/pull/466 should make the rms_norm backward check pass:
`python benchmarks/run.py --kernel rms_norm --bwd --metrics speedup,accuracy --num-inputs 1 --latency-measure-mode profiler`
=> rms_norm: get weight from function args

.github/workflows/test.yml
CI error: https://github.com/pytorch/helion/actions/runs/17997155423/job/51198778661?pr=679
```
______________________ ERROR collecting test/test_misc.py ______________________
ImportError while importing test module '/__w/helion/helion/test/test_misc.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/github/home/.local/share/uv/python/cpython-3.10.18-linux-x86_64-gnu/lib/python3.10/importlib/__init__.py:126: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
test/test_misc.py:15: in <module>
from torch.testing._internal.common_utils import instantiate_parametrized_tests
.venv/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py:96: in <module>
from torch.utils import cpp_extension …
```
=> [CI] Fix missing setuptools

examples/rms_norm.py, test/test_examples.expected, test/test_examples.py
A fused, semi-persistent (keeps dw around a bit) kernel that showcases subtiling. In my measurements, two kernels > single kernel without subtiling > single kernel with subtiling in terms of latency. However, running bwd with `benchmark/run.py` seems buggy. Would love to try it eventually.
=> faster rms norm backwards kernel

helion/autotuner/base_search.py
* #693
* #677
* #654
* #692
* __->__#691
--- --- ---
Increase tolerance for _validate_against_baseline
I've been seeing false-alarm failures from this for fp16 kernels.
=> Increase tolerance for _validate_against_baseline

helion/autotuner/base_search.py, helion/runtime/settings.py
* #696
* #677
* #654
* #693
* #695
* __->__#692
--- --- ---
Support HELION_AUTOTUNE_ACCURACY_CHECK=0
=> Support HELION_AUTOTUNE_ACCURACY_CHECK=0

examples/rms_norm.py, test/test_examples.expected
about doubles perf for B=32K, H=2K, presumably before was storing a bunch into inv_sqrt?
might also indicate something funny happening with keepdim.
=> rms norm: improve fwd perf

helion/autotuner/logger.py
I believe this error can happen for some configs, and it's recoverable.
Fixes https://github.com/pytorch/helion/issues/470.
=> [Autotune] Skip Triton shared memory OOM

.github/workflows/test.yml
* #696
* #677
* #654
* __->__#697
* #693
* #695
--- --- ---
Increase test timeout to 60
I am seeing jobs unstable because they hit the timeout
=> Increase test timeout to 60

benchmarks/run.py
Before this PR, it times out at 6 hours: https://github.com/pytorch/helion/actions/runs/18057174753/job/51388536865
=> [Benchmark CI] Run fewer inputs for layer_norm-bwd to avoid job timeout

benchmarks/run.py
So that autotuner-discovered configs can pass tritonbench's accuracy test.
Example benchmark CI job where `layer_norm` currently fails tritonbench's accuracy check: https://github.com/pytorch/helion/actions/runs/18057174753/job/51388536866.
=> [Benchmark CI] Set tolerance values that match autotuner setting

benchmarks/run.py
`rms_norm-bwd` has 6 inputs total, but last input raises Triton OOM at default config: https://github.com/pytorch/helion/issues/711 and still needs debugging.
=> [Benchmark CI] Skip last input shape for rms_norm-bwd

helion/autotuner/differential_evolution.py
* #696
* __->__#677
* #654
--- --- ---
I've been seeing improvements in generation 35 for more complex kernels.
=> Increase default num_generations to 40

helion/_compiler/device_ir.py, helion/_compiler/matmul_utils.py, test/test_dot.py
Fixes https://github.com/pytorch/helion/issues/511.
The original issue is that make_fx tracing of torch.matmul with 3D inputs creates several view ops, and it's difficult to preserve the correct symbols through all the view ops. The approach implemented in this PR is the cleanest way I could find to support torch.matmul with 3D inputs (by dispatching it to torch.bmm instead).
=> Support torch.matmul with 3D inputs

benchmarks/run.py, examples/exp.py, test/test_examples.expected, test/test_examples.py
Test Plan:
Adding new unit tests in test_examples.py
Testing with run.py and exp.py
=> Add backward kernel for exp

helion/_compat.py, helion/runtime/__init__.py
Intel Triton supports Tensor-Descriptor from 3.5 to map Tensor-Descriptor to the 2d-block-load that XPU hardware has supported well. So, XPU only needs to check the Triton version.
=> Enable tensor descriptor for XPU

helion/_testing.py, helion/autotuner/base_search.py, helion/autotuner/local_cache.py
This PR intends to fix the issue that the produced kernels for XPU cannot be cached well under the Helion cache directory. 
Meanwhile, the PR changes the `DEVICE`  to `XPU` if `torch.xpu.is_available()` is `True` to pass the `test_cache.py`. Otherwise, an assertion error will be raised - `AssertionError: Torch not compiled with CUDA enabled`
=> Fix the issue that the XPU kernels cannot be cached well

helion/_compiler/compile_environment.py, test/test_logging.py
Stacked PRs:
* __->__#771
--- --- ---
With `TORCH_LOGS="+dynamic"`, now it prints:
```
I1001 20:49:16.995000 1208064 torch/fx/experimental/symbolic_shapes.py:4800] create_unbacked_symint u0 [-int_oo, int_oo]
I1001 20:49:16.995000 1208064 torch/fx/experimental/symbolic_shapes.py:4800] Helion kernel stack:
I1001 20:49:16.995000 1208064 torch/fx/experimental/symbolic_shapes.py:4800]   File "/home/willfeng/local/helion2/minimal_repro.py", line 10, in logging_reduce_rows
I1001 20:49:16.995000 1208064 torch/fx/experimental/symbolic_shapes.py:4800]     m_block = hl.register_block_size(m)
I1001 20:49:16.995000 1208064 torch/fx/experimental/symbolic_shapes.py:4800]               ^^^^^^^^^^^^^^^^^^^^^^^^^
```
which can be further traced with `TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u0"`
=> Print Helion kernel source line in symbolic shape debugging

helion/_compiler/generate_ast.py, test/test_rng.expected
Currently, the RNG operations in Helion only support `CUDA` as the device name is hard-coded as `cuda` to produce the RNG seed buffer. This PR intends to generalize the code by replacing `torch.device('cuda')` with `torch.accelerator.current_accelerator()`.
=> Add XPU support for RNG operations

helion/autotuner/logger.py
Adds expected Level Zero driver error that occurs for invalid kernel configurations using XPU backend.
=> Handle XPU compilation error

test/test_examples.py, test/test_misc.py, test/test_print_ref_eager_mode.py, test/test_ref_eager.py, test/test_tensor_descriptor.py, test/test_type_propagation.expected, test/test_type_propagation.py
=> Generalize the cuda-bias test cases by replacing hardcoded "cuda" literal with the DEVICE variable

helion/autotuner/base_search.py, helion/autotuner/benchmarking.py, pyproject.toml, requirements.txt
Stacked PRs:
* __->__#786
--- --- ---
=> Make progress bar prettier

.pre-commit-config.yaml, benchmarks/run.py, lint.sh
* #791
* __->__#790
--- --- ---
Upgrade ruff==0.13.3 pyright==1.1.406
=> Upgrade ruff==0.13.3 pyright==1.1.406

test/test_print.py, test/test_tensor_descriptor.py
=> Generalize test_print and test_tensor_descriptor to support different accelerators

helion/autotuner/base_search.py
* #800
* #799
* #788
* __->__#789
--- --- ---
Limit rebench to 1000 iterations
For ulta-tiny sizes we would do 10k+ iterations, which is slow.
=> Limit rebench to 1000 iterations

examples/grouped_gemm.py, helion/_compiler/type_propagation.py, test/test_examples.expected
Currently, the `grouped_gemm_jagged_persistent` in `examples/grouped_gemm.py` gets the number of workers by querying `multi_processor_count` of device properties for CUDA. XPU provides a similar API. This PR intends to extend the support to XPU.
=> Enable torch.xpu._XpuDeviceProperties in Helion kernel

helion/_compiler/tile_strategy.py, test/test_tensor_descriptor.py
This fixes https://github.com/pytorch/helion/issues/755 and unblocks faster JSD kernel: https://github.com/pytorch/helion/pull/733.
=> Set range_num_stages <= 1 if using tensor_descriptor, to avoid CUDA misaligned address error

helion/_compiler/matmul_utils.py, helion/language/matmul_ops.py, test/test_dot.py
* #812
* #814
* __->__#813
--- --- ---
Add out_dtype arg to hl.dot
Fixes #747
=> Add out_dtype arg to hl.dot

docs/api/settings.md, helion/autotuner/differential_evolution.py, helion/autotuner/pattern_search.py, helion/runtime/settings.py, test/test_autotuner.py
The maximum number of generations was hardcoded to 100 for pattern search and to 40 for differential evolution search.
This autotune_max_generations setting (HELION_AUTOTUNE_MAX_GENERATIONS env variable) allows users to override the default max, which is now set to 40 by default for both search algorithms.
This setting can be applied to either the pattern search or the differential evolution search algorithms.
=> Adding new setting, autotune_max_generations, that allows user to set the maximum number of generations for autotuning

.github/workflows/benchmark.yml, benchmarks/run.py
Stacked PRs:
* __->__#820
--- --- ---
=> [Benchmark] Keep going when a single benchmark fails

examples/jsd.py, test/test_examples.expected, test/test_examples.py
Stacked PRs:
* __->__#733
--- --- ---
Benchmarking command: `HELION_USE_DEFAULT_CONFIG=0 HELION_PRINT_OUTPUT_CODE=1 HELION_AUTOTUNE_ACCURACY_CHECK=1 HELION_AUTOTUNE_RANDOM_SEED=0 CUDA_VISIBLE_DEVICES=7 python benchmarks/run.py --op jsd --num-inputs 3 --metrics speedup 2>&1 | tee ~/test_helion.log`
```
(B, T, V)    liger_jsd-speedup    torch_compile_jsd-speedup    helion_jsd_tritonbench-speedup
----------------  -------------------  ---------------------------  --------------------------------
(4, 2048, 4096)             3.07473                       8.75428                           8.20297
(4, 2048, 8192)             3.33668                       9.41338                           9.06205
(4, 2048, 16384)             0.587061                      9.38754                           8.82071 …
```
=> Faster Helion JSD

helion/_testing.py, test/test_constexpr.py, test/test_examples.py, test/test_reductions.expected, test/test_signal_wait.py, test/test_type_propagation.expected
This PR covers:
- Normalize device name to support `device(type='cuda', index=0) `
- Skip the test cases that are not applicable
- Skip `test_template_via_closure1` for XPU due to https://github.com/pytorch/helion/issues/795
=> Normalize device name and decorate cuda-only test cases
