- helion/_compiler/device_ir.py
- test/data/basic_kernels.py
- test/test_generate_ast.py
> Implement subscript on lhs of AugAssign: x[tile] *= 2

- helion/_compiler/compile_environment.py
- test/test_misc.py
> Support list, tuple and dict inputs

- examples/bmm.py
- helion/_compiler/inductor_lowering.py
- helion/runtime/kernel.py
- test/test_examples.py
Dependent on https://github.com/pytorch/pytorch/pull/153513.
* __->__ #39
> dense bmm support

- .pre-commit-config.yaml
- README.md
- helion/_testing.py
- helion/autotuner/config_spec.py
- helion/runtime/config.py
- helion/runtime/kernel.py
- pyproject.toml
- requirements.txt
Stacked PRs:
* __->__#49
--- --- ---
Add the core properties to Config object
> Add the core properties to Config object

- helion/_compiler/generate_ast.py
- helion/_compiler/inductor_lowering.py
- test/test_misc.py
> Support torch factory functions inside device loop

- helion/_compat.py
Differential Revision: D75115325
> Fix more unit tests

- test/test_matmul.py
`test_matmul_tensor_descriptor` is broken because the CI couldn't run it (CI gpu doesn't have TMA).
> Fix test_matmul_tensor_descriptor unit test

- helion/_compiler/compile_environment.py
- helion/_compiler/type_propagation.py
- helion/language/loops.py
- test/test_loops.py
Stacked PRs:
* #83
* __->__#82
--- --- ---
> Add support for hl.tile(begin, end) and hl.tile(begin, end, block_size)

- helion/_compiler/compile_environment.py
- helion/_compiler/device_ir.py
- helion/_compiler/tile_index_proxy.py
- helion/_compiler/type_propagation.py
- helion/language/__init__.py
- helion/language/loops.py
- helion/language/tiles.py
- helion/runtime/kernel.py
- test/test_indexing.py
Stacked PRs:
* __->__#89
--- --- ---
> Add hl.tile_index()

- pyproject.toml
previous version of the project on PyPI was 0.0.1, so this updates that to be in sync, and now that i pushed 0.0.2 lets move forward
https://pypi.org/project/helion/0.0.2/
> Bump project version

- pyproject.toml
Stacked PRs:
* #104
* __->__#103
--- --- ---
> Swap to using hatch vcs

- .pre-commit-config.yaml
Stacked PRs:
* __->__#106
--- --- ---
> Beef up pre-commit checks

- examples/jagged_dense_add.py
- helion/_compiler/indexing_strategy.py
- helion/_compiler/tile_strategy.py
- helion/exc.py
- helion/language/loops.py
- test/test_atomic_add.py
- test/test_broadcasting.py
- test/test_closures.py
- test/test_constexpr.py
- test/test_control_flow.py
- test/test_examples.py
- test/test_generate_ast.py
- test/test_indexing.py
- test/test_loops.py
- test/test_matmul.py
- test/test_misc.py
- test/test_reductions.py
- test/test_specialize.py
Stacked PRs:
* __->__#105
--- --- ---
> Add jagged_dense_add_2d example in generalize tensor indexing

- README.md
> Update README.md with Helion logo

- helion/_compiler/device_ir.py
- helion/_compiler/inductor_lowering.py
- helion/_compiler/node_masking.py
- helion/_compiler/roll_reduction.py
- helion/language/_tracing_ops.py
- test/test_examples.py
- test/test_loops.py
- test/test_masking.py
- test/test_misc.py
Stacked PRs:
* #112
* __->__#111
--- --- ---
> Improve mask optimization to cover control flow and inductor ops

- README.md
- helion/_compiler/indexing_strategy.py
- test/test_loops.py
Stacked PRs:
* #116
* #115
* __->__#113
* #114
--- --- ---
I don't think this was correct, since the grid index shouldn't get
expanded.
> Remove 'first_non_grid_index' for hl.grid index

- helion/_compiler/device_ir.py
- helion/_compiler/inductor_lowering.py
- helion/_compiler/node_masking.py
- helion/_compiler/roll_reduction.py
Stacked PRs:
* #117
* __->__#116
* #115
--- --- ---
> Replace torch.fx.GraphModule with torch.fx.Graph

- examples/moe_matmul_ogs.py
- helion/_compiler/tile_dispatch.py
- test/test_examples.py
Adapted from https://github.com/triton-lang/triton/blob/main/python/triton_kernels/triton_kernels/matmul_ogs_details/_matmul_ogs.py.
> MoE matmul example 

- .pre-commit-config.yaml
- linter/check_main.py
Stacked PRs:
* __->__#119
--- --- ---
In order to make sure examples can be run in FBCode, we need them to have main functions.
> Add pre-commit hook to make sure examples have a main function

- helion/_compiler/compile_environment.py
- helion/_compiler/tile_dispatch.py
- helion/_compiler/type_propagation.py
- helion/autotuner/config_fragment.py
- helion/autotuner/config_spec.py
- helion/language/loops.py
- test/test_loops.py
Stacked PRs:
* __->__#117
* #116
* #115
--- --- ---
> Make loop reordering work with register_block_size

- README.md
- helion/_compiler/compile_environment.py
- helion/_compiler/tile_dispatch.py
- helion/_compiler/type_propagation.py
- helion/autotuner/config_spec.py
- helion/language/loops.py
- helion/runtime/config.py
- test/test_autotuner.py
- test/test_loops.py
Stacked PRs:
* __->__#122
* #121
--- --- ---
> Make l2_grouping work with register_block_size

- helion/_compiler/type_propagation.py
- helion/exc.py
- test/test_errors.py
Stacked PRs:
* #132
* #131
* #130
* #129
* #128
* #127
* __->__#126
--- --- ---
> Improve error message for overpacked tiles

- helion/_compiler/device_ir.py
- helion/_compiler/tile_dispatch.py
- helion/autotuner/config_spec.py
- test/test_specialize.py
Stacked PRs:
* #132
* #131
* #130
* #129
* __->__#128
* #127
* #126
--- --- ---
> Refactor reduction loop config spec

- helion/autotuner/block_id_sequence.py
- helion/autotuner/config_spec.py
Stacked PRs:
* #132
* #131
* #130
* __->__#129
* #128
* #127
* #126
--- --- ---
> Move BlockIdSequence to its own file

- README.md
- examples/add.py
- examples/attention.py
- examples/bmm.py
- examples/concatenate.py
- examples/embedding.py
- examples/long_sum.py
- examples/matmul.py
- examples/moe_matmul_ogs.py
- examples/softmax.py
- helion/autotuner/base_search.py
Stacked PRs:
* #135
* #134
* __->__#133
--- --- ---
do_bench returns ms rather than sec
> Correct units for time printouts

- helion/_compiler/compile_environment.py
- helion/_compiler/device_function.py
- helion/_compiler/device_ir.py
- helion/_compiler/generate_ast.py
- helion/_compiler/indexing_strategy.py
- helion/_compiler/roll_reduction.py
- helion/_compiler/tile_dispatch.py
- helion/_compiler/tile_strategy.py
- helion/_compiler/type_propagation.py
- helion/_compiler/variable_origin.py
- helion/language/loops.py
Stacked PRs:
* #135
* __->__#134
--- --- ---
Some minor refactoring to make naming more consistent
> Rename block_size_idx to block_id

- helion/_compiler/device_ir.py
- helion/_compiler/generate_ast.py
- helion/_compiler/reduction_strategy.py
- helion/_compiler/tile_dispatch.py
- helion/_compiler/tile_strategy.py
- helion/autotuner/block_id_sequence.py
- helion/language/loops.py
Stacked PRs:
* __->__#135
* #134
--- --- ---
Some minor refactoring to make naming more consistent
> Rename block_indices to block_ids

- .pre-commit-config.yaml
This tests Pyre's pre-commit hook from a forked repo as a test
> Add Pyre Pre-Commit Hook

- helion/_compiler/type_propagation.py
- test/test_control_flow.py
Stacked PRs:
* __->__#138
--- --- ---
> Fix bug with errors on unreachable if branch

- helion/_compiler/type_propagation.py
- helion/autotuner/block_id_sequence.py
- helion/exc.py
- test/test_errors.py
Stacked PRs:
* __->__#139
--- --- ---
[Error Message] Update block config size length mismatch
> [Error Message] Update block config size length mismatch

- helion/_compat.py
- helion/_compiler/compile_environment.py
- helion/_logging/_internal.py
- helion/autotuner/base_search.py
- helion/autotuner/logger.py
- test/test_logging.py
Stacked PRs:
* __->__#141
* #142
--- --- ---
> Fix some typos

- helion/_compiler/ast_read_writes.py
Stacked PRs:
* __->__#148
--- --- ---
> Fix ast read writes

- .gitignore
- helion/_compiler/compile_environment.py
- helion/_compiler/device_ir.py
- helion/_compiler/generate_ast.py
- helion/_compiler/indexing_strategy.py
- helion/_compiler/reduction_strategy.py
- helion/_compiler/tile_dispatch.py
- helion/_compiler/tile_index_proxy.py
- helion/_compiler/tile_strategy.py
- helion/_compiler/type_propagation.py
- helion/language/__init__.py
- helion/language/_tracing_ops.py
- helion/language/loops.py
- helion/language/memory_ops.py
- helion/language/tiles.py
- test/test_indexing.py
- test/test_matmul.py
Stacked PRs:
* #154
* #152
* #151
* __->__#150
--- --- ---
Support hl.tile_{begin,end,block_size}
> Support hl.tile_{begin,end,block_size}

- test/test_matmul.py
Stacked PRs:
* #154
* __->__#155
--- --- ---
Increase atol for test_matmul_split_k
> Increase atol for test_matmul_split_k

- helion/_compiler/device_function.py
- helion/_compiler/generate_ast.py
- helion/_compiler/inductor_lowering.py
- helion/_compiler/program_id.py
- helion/_compiler/reduction_strategy.py
- helion/_compiler/tile_strategy.py
- helion/_compiler/variable_origin.py
- helion/language/_tracing_ops.py
- helion/language/loops.py
- helion/language/tiles.py
- test/test_register_tunable.py
Stacked PRs:
* #162
* #161
* #160
* #159
* __->__#157
--- --- ---
Fix bug with computations based on hl.register_block_size
> Fix bug with computations based on hl.register_block_size

- test/test_loops.py
- test/test_matmul.py
Stacked PRs:
* __->__#162
* #161
* #160
* #159
* #157
--- --- ---
Unskip some previosly failing tests
> Unskip some previosly failing tests

- .github/workflows/test.yml
Stacked PRs:
* __->__#168
--- --- ---
> Use workflow matrix to deduplicate code

- test/test_masking.py
Stacked PRs:
* #184
* #183
* __->__#182
--- --- ---
Failing on my H100
> Relax bounds on test_mask_dot

- helion/runtime/kernel.py
Stacked PRs:
* #184
* __->__#183
--- --- ---
> Do not precompile set configs

- helion/exc.py
- helion/runtime/kernel.py
- helion/runtime/settings.py
- test/test_autotuner.py
Stacked PRs:
* __->__#184
* #183
--- --- ---
> Add option to ban/disallow autotuning

- README.md
* #192
* #195
* __->__#193
--- --- ---
Recommend PyTorch nightly build in readme
> Recommend PyTorch nightly build in readme

- helion/language/tile_ops.py
- test/test_misc.py
* #192
* __->__#195
--- --- ---
Fix issue with ConfigSpec mutation in codegen
Fixes #185
> Fix issue with ConfigSpec mutation in codegen

- helion/_compiler/compile_environment.py
- helion/_compiler/device_function.py
- helion/_compiler/generate_ast.py
- helion/_compiler/indexing_strategy.py
- helion/_compiler/inductor_lowering.py
- helion/_compiler/reduction_strategy.py
- helion/_compiler/tile_strategy.py
- helion/language/tile_ops.py
- test/test_matmul.py
- test/test_register_tunable.py
* __->__#192
* #195
--- --- ---
Improve loop end bound optimization for nested tiling
> Improve loop end bound optimization for nested tiling

- helion/runtime/settings.py
* __->__#197
--- --- ---
Set default dot_precision to TRITON_F32_DEFAULT
Fixes #196
> Set default dot_precision to TRITON_F32_DEFAULT

- helion/_compiler/type_propagation.py
* #204
* #203
* __->__#201
* #202
* #200
--- --- ---
Fix typo in LiteralType.merge
> Fix typo in LiteralType.merge

- helion/_compiler/device_ir.py
- helion/exc.py
- test/test_errors.py
* #213
* #212
* #211
* #210
* #209
* #208
* #206
* __->__#205
--- --- ---
Add InvalidDeviceForLoop exception type
> Add InvalidDeviceForLoop exception type

- test/test_loops.py
* #215
* __->__#214
--- --- ---
Relax chebyshev kernel test tolerance
> Relax chebyshev kernel test tolerance

- helion/_compiler/compile_environment.py
- helion/_compiler/inductor_lowering.py
- helion/language/__init__.py
- helion/language/creation_ops.py
- helion/language/tile_ops.py
- test/test_indexing.py
* __->__#215
* #214
--- --- ---
Add support for torch.arange
> Add support for torch.arange

- test/test_indexing.py
Stacked PRs:
* __->__#236
--- --- ---
> Enable Test fixed by Fixed by #195

- helion/_compat.py
- helion/_compiler/inductor_lowering.py
- test/test_autotuner.py
- test/test_grid.py
* #241
* #240
* __->__#244
--- --- ---
Fix failing tests on main
There was an upstream triton change to min_dot_size.
> Fix failing tests on main

- .gitignore
- benchmark/README.md
- benchmark/run.py
Stacked PRs:
* #248
* __->__#247
--- --- ---
Original PR: https://github.com/pytorch-labs/helion/pull/242
> [Benchmark] Add initial TritonBench integration and vector_add benchmark example

- benchmark/run.py
- examples/exp.py
Stacked PRs:
* #253
* #252
* __->__#249
--- --- ---
> [Benchmark] Add vector_exp benchmark

- .pre-commit-config.yaml
- examples/all_gather_matmul.py
- helion/_compiler/type_propagation.py
- helion/language/signal_wait.py
- pyproject.toml
- scripts/dictionary.txt
- test/test_loops.py
- test/test_persistent_kernels.py
Stacked PRs:
* __->__#265
--- --- ---
> [BE] Add spellchecker

- helion/_compiler/helper_function.py
- helion/_compiler/node_masking.py
- helion/_compiler/source_location.py
- helion/_compiler/traceback_compat.py
- helion/_compiler/type_propagation.py
- helion/autotuner/base_search.py
- helion/autotuner/differential_evolution.py
- helion/autotuner/finite_search.py
- helion/autotuner/random_search.py
- helion/runtime/kernel.py
- helion/runtime/settings.py
* #276
* __->__#274
--- --- ---
Remove pyre-ignore/pyre-fixme calls
We no longer use pyre
> Remove pyre-ignore/pyre-fixme calls

- helion/runtime/kernel.py
* #273
* #272
* #271
* __->__#270
--- --- ---
Improve typing for helion.kernel
> Improve typing for helion.kernel

- examples/jagged_mean.py
- test/test_examples.expected
- test/test_examples.py
Stacked PRs:
* #268
* #267
* #264
* __->__#263
--- --- ---
> Add jagged_mean example

- examples/fp8_gemm.py
- helion/_compiler/inductor_lowering.py
- test/test_examples.expected
- test/test_examples.py
Stacked PRs:
* #268
* __->__#267
* #264
* #263
--- --- ---
> Add fp8_gemm example and test

- benchmarks/run.py
Stacked PRs:
* __->__#268
* #267
* #264
* #263
--- --- ---
> [Benchmark] Add fp8_gemm to TritonBench integration

- helion/language/device_print.py
- helion/language/loops.py
- helion/language/memory_ops.py
- helion/runtime/kernel.py
- helion/runtime/settings.py
* __->__#276
--- --- ---
Fix some pyright errors
This is mostly AI generated.
> Fix some pyright errors

- README.md
- helion/exc.py
- helion/runtime/settings.py
* #277
* #273
* #272
* __->__#271
--- --- ---
Remove unused exception types
> Remove unused exception types

- helion/language/constexpr.py
- helion/language/creation_ops.py
- helion/language/loops.py
- helion/language/memory_ops.py
- helion/language/reduce_ops.py
- helion/language/scan_ops.py
- helion/language/view_ops.py
- helion/runtime/kernel.py
* #277
* #273
* __->__#272
* #271
--- --- ---
Fix docstring see also lists
> Fix docstring see also lists

- .github/workflows/docs-test.yml
- .gitignore
- docs/Makefile
- docs/README.md
- docs/api/autotuner.md
- docs/api/config.md
- docs/api/exceptions.md
- docs/api/index.md
- docs/api/kernel.md
- docs/api/language.md
- docs/api/runtime.md
- docs/api/settings.md
- docs/conf.py
- docs/index.md
- docs/installation.md
- helion/language/tile_ops.py
- pyproject.toml
* #277
* __->__#273
--- --- ---
Initial versison of documentation
> Initial versison of documentation

- .github/workflows/docs-deploy.yml
* __->__#277
* #273
--- --- ---
Deploy docs to github pages
> Deploy docs to github pages

- .github/workflows/lint.yml
- benchmarks/run.py
- pyproject.toml
* #282
* __->__#281
--- --- ---
Fix lint error on main
> Fix lint error on main

- README.md
- docs/README.md
- docs/index.md
* __->__#282
* #281
--- --- ---
Add a link to the documentation
> Add a link to the documentation

- benchmarks/run.py
Stacked PRs:
* #279
* #280
* __->__#278
--- --- ---
> [Benchmark] Fix tritonbench integration due to upstream changes

- helion/_compiler/type_propagation.py
- test/test_indexing.expected
- test/test_indexing.py
* __->__#285
--- --- ---
Add implicit broadcasting tests
> Add implicit broadcasting tests

- README.md
- docs/index.md
* #292
* #291
* #290
* __->__#288
* #287
--- --- ---
Update autotuning example in docs
> Update autotuning example in docs

- helion/_compiler/ast_read_writes.py
- helion/_compiler/device_function.py
- helion/_compiler/generate_ast.py
- test/test_broadcasting.expected
- test/test_control_flow.expected
- test/test_examples.expected
- test/test_loops.expected
- test/test_masking.expected
- test/test_misc.expected
- test/test_signal_wait.expected
- test/test_specialize.expected
Stacked PRs:
* __->__#289
--- --- ---
> Add host side dead code elimination

- benchmarks/run.py
Stacked PRs:
* #293
* #286
* #279
* __->__#284
--- --- ---
> [Benchmark] Add attention tritonbench integration

- docs/api/exceptions.md
- helion/_compiler/type_propagation.py
- helion/exc.py
- helion/language/loops.py
- test/data/all_ast_nodes.py
- test/test_errors.py
- test/test_reductions.expected
- test/test_type_propagation.expected
* #297
* #296
* #295
* #292
* #291
* __->__#290
--- --- ---
Add helion.exc.CannotModifyHostVariableOnDevice and helion.exc.CannotReadDeviceVariableOnHost
I'm trying to improve error messages.
> Add helion.exc.CannotModifyHostVariableOnDevice and helion.exc.CannotReadDeviceVariableOnHost

- helion/runtime/kernel.py
- test/test_misc.py
* #300
* #297
* #296
* #295
* #292
* __->__#291
* #299
--- --- ---
> Make to_triton_code config arg optional

- docs/api/exceptions.md
- helion/_compiler/device_ir.py
- helion/exc.py
- test/test_errors.py
* #300
* #297
* #296
* #295
* __->__#292
* #291
* #299
--- --- ---
> Add helion.exc.DeviceTensorSubscriptAssignmentNotAllowed

- helion/_compiler/compile_environment.py
- helion/_compiler/indexing_strategy.py
- test/test_tensor_descriptor.py
* #300
* #297
* __->__#296
* #295
* #292
* #291
* #299
--- --- ---
> Fix bug with tensor descriptor and small block size

- helion/_compiler/helper_function.py
* #300
* __->__#297
* #296
* #295
* #292
* #291
* #299
--- --- ---
> Relax typing for CombineFunction

- docs/api/exceptions.md
- helion/_compiler/device_ir.py
- helion/exc.py
- helion/language/_decorators.py
- helion/language/_tracing_ops.py
- helion/language/memory_ops.py
- helion/language/signal_wait.py
- test/test_errors.py
* #307
* __->__#306
--- --- ---
Add error for using a host tensor directly
> Add error for using a host tensor directly

- helion/_compiler/type_propagation.py
- test/test_misc.expected
- test/test_misc.py
* __->__#307
* #306
--- --- ---
Improve Tensor.item() handling
> Improve Tensor.item() handling

- helion/_compiler/device_ir.py
- helion/_compiler/generate_ast.py
Stacked PRs:
* __->__#294
--- --- ---
> Fix type_info null errors

- benchmarks/run.py
Stacked PRs:
* #309
* #308
* #305
* #304
* #302
* #293
* #279
* __->__#286
--- --- ---
> [Benchmark] Add softmax tritonbench integration

- examples/matmul_layernorm.py
- helion/__init__.py
- helion/_compiler/device_ir.py
- helion/_compiler/lift_closures.py
- helion/_compiler/node_masking.py
- helion/_compiler/roll_reduction.py
- helion/_compiler/tile_dispatch.py
- helion/_compiler/type_propagation.py
- helion/autotuner/config_generation.py
- helion/autotuner/config_spec.py
- helion/autotuner/random_search.py
- helion/language/_decorators.py
- helion/language/_tracing_ops.py
- helion/language/loops.py
- helion/language/memory_ops.py
- helion/language/signal_wait.py
- helion/language/tile_proxy.py
- helion/runtime/config.py
* #315
* #314
* #313
* __->__#310
--- --- ---
Make import relative
> Make imports relative

- helion/_compiler/device_function.py
- helion/_compiler/generate_ast.py
- helion/_compiler/host_function.py
- helion/_compiler/output_header.py
- helion/autotuner/base_search.py
- helion/runtime/__init__.py
- helion/runtime/kernel.py
- test/test_associative_scan.expected
- test/test_atomic_add.expected
- test/test_broadcasting.expected
- test/test_closures.expected
- test/test_constexpr.expected
- test/test_control_flow.expected
- test/test_examples.expected
- test/test_generate_ast.expected
- test/test_grid.expected
- test/test_indexing.expected
- test/test_loops.expected
- test/test_masking.expected
- test/test_matmul.expected
- test/test_misc.expected
- test/test_persistent_kernels.expected
- test/test_persistent_kernels.py
- test/test_reduce.expected
- test/test_reductions.expected
- test/test_register_tunable.expected
- test/test_signal_wait.expected
- test/test_specialize.expected
- test/test_tensor_descriptor.expected
- test/test_views.expected
* #317
* #316
* #315
* __->__#314
* #313
--- --- ---
Remove make_precompiler generated wrapper
> Remove make_precompiler generated wrapper

- benchmarks/run.py
Stacked PRs:
* __->__#321
* #320
* #325
--- --- ---
> [Benchmark] Add cross_entropy to tritonbench integration

- helion/_compiler/device_function.py
- helion/_compiler/device_ir.py
- helion/_compiler/helper_function.py
- helion/language/reduce_ops.py
- helion/language/scan_ops.py
- test/test_associative_scan.expected
- test/test_associative_scan.py
- test/test_examples.expected
- test/test_reduce.expected
- test/test_reduce.py
* #329
* #328
* __->__#323
--- --- ---
Improve naming for generated helper functions
> Improve naming for generated helper functions

- .github/workflows/lint.yml
Stacked PRs:
* #351
* #350
* __->__#349
--- --- ---
> Run lint with nightly (match test CI)

- helion/runtime/kernel.py
Stacked PRs:
* __->__#350
* #351
--- --- ---
> Sanitize device rank from in memory cache

- helion/runtime/kernel.py
Stacked PRs:
* #350
* __->__#351
--- --- ---
> Refactor BoundKernel in memory caching

- helion/_compiler/compile_environment.py
- test/test_constexpr.expected
- test/test_constexpr.py
* #355
* #354
* __->__#353
--- --- ---
Allow string literal args
> Allow string literal args

- helion/_testing.py
- test/test_examples.py
* __->__#355
* #354
* #353
--- --- ---
Fix test_fp8_attention expected
This was triggering autotuning and making tests take 10+ minutes
> Fix test_fp8_attention expected

- .github/workflows/test.yml
Stacked PRs:
* #363
* __->__#362
--- --- ---
> Refresh the action cache once a month

- .github/workflows/test.yml
Stacked PRs:
* __->__#365
--- --- ---
> Remove triton's conda deps

- .github/workflows/lint.yml
Stacked PRs:
* #367
* __->__#366
--- --- ---
> Make lint workflow leaner

- .github/workflows/test.yml
Stacked PRs:
* __->__#368
--- --- ---
> Swap from conda to uv on test workflow

- helion/_compiler/inductor_lowering_extra.py
- test/test_reductions.expected
- test/test_reductions.py
- test/test_views.expected
* __->__#361
* #357
--- --- ---
Add fallbacks for unary ops that don't support fp16
> Add fallbacks for unary ops that don't support fp16

- helion/_compiler/indexing_strategy.py
- test/test_indexing.expected
- test/test_indexing.py
Stacked PRs:
* #348
* __->__#360
--- --- ---
> Only use Tensor Descriptor indexing with appropriate shapes

- benchmarks/run.py
- examples/layer_norm.py
- test/test_examples.expected
- test/test_examples.py
Stacked PRs:
* __->__#348
* #360
--- --- ---
> LayerNorm Example

- helion/autotuner/base_search.py
Stacked PRs:
* __->__#374
--- --- ---
> Do not crash autotuner on more triton/llvm/cuda errors seen on B200

- helion/autotuner/base_cache.py
- helion/autotuner/local_cache.py
- helion/runtime/kernel.py
- test/test_cache.py
Stacked PRs:
* #394
* __->__#388
--- --- ---
> Use autotuner's BoundKernel in caching

- helion/autotuner/base_cache.py
- test/test_cache.py
* __->__#415
* #414
* #413
* #412
* #411
--- --- ---
Add metaclass [] syntax for cache classes
> Add metaclass [] syntax for cache classes

- test/test_signal_wait.expected
Stacked PRs:
* __->__#432
--- --- ---
> Fix: test/test_signal_pad

- helion/_compiler/roll_reduction.py
- helion/language/memory_ops.py
- helion/language/tile_proxy.py
- test/test_indexing.py
Stacked PRs:
* #426
* #425
* __->__#424
--- --- ---
> Fix scalar value assignment to tensor slices

- helion/_compiler/type_propagation.py
- test/test_errors.py
- test/test_indexing.py
Stacked PRs:
* #426
* __->__#425
* #424
--- --- ---
> Fix scalar tensor broadcasting in type propagation

- docs/conf.py
- examples/README.rst
Making the example page bullet points clickable. Also edits generated index page to remove the links and images that sphinx-gallery adds
> Make bullet points clickable

- benchmarks/run.py
It causes issues in fbcode integration.
> [Benchmark] Avoid using _run in TritonBench integration

- .github/workflows/test.yml
Stacked PRs:
* #441
* __->__#436
--- --- ---
> Add B200 CI

- helion/autotuner/base_search.py
Stacked PRs:
* #455
* __->__#453
--- --- ---
Fixes #451
> Skip illegal memory access for autotuning

- docs/api/index.md
- docs/api/language.md
- helion/language/signal_wait.py
Stacked PRs:
* __->__#478
--- --- ---
> Improve signal/wait doc

- .github/matrix.json
- .github/workflows/test.yml
Stacked PRs:
* #471
* #441
* __->__#449
--- --- ---
> Cleanup ci

- .github/matrix.json
- helion/_testing.py
- test/test_autotuner.py
- test/test_dot.py
- test/test_examples.py
- test/test_indexing.py
- test/test_inline_asm_elementwise.py
- test/test_print.py
- test/test_register_tunable.py
- test/test_signal_wait.py
Stacked PRs:
* #471
* __->__#441
--- --- ---
> Run CI on mi325x

- docs/api/language.md
- helion/language/__init__.py
- helion/language/stack_tensor.py
Stack Info: 
https://github.com/pytorch/helion/pull/478
> Improve Stacktensor Doc

- .github/workflows/test.yml
- test/test_autotuner.py
- test/test_indexing.py
- test/test_views.py
Stacked PRs:
* __->__#471
--- --- ---
> Require tests to be faster than 30s

- helion/autotuner/base_search.py
- helion/exc.py
Stacked PRs:
* __->__#455
* #453
--- --- ---
> Improve error message when no good config is found

- .gitignore
- helion/_compiler/inductor_lowering.py
- helion/exc.py
- test/test_reductions.expected
- test/test_reductions.py
* #502
* __->__#499
--- --- ---
Fix handling of fixed size reductions
Fixes #498
> Fix handling of fixed size reductions

- helion/_compiler/device_function.py
- test/test_broadcasting.expected
- test/test_broadcasting.py
- test/test_specialize.expected
* __->__#506
--- --- ---
Fixes #493
> Fix issue with fp64 constants

- helion/_compiler/inductor_lowering.py
- test/test_indexing.expected
- test/test_indexing.py
Part of https://github.com/pytorch/helion/issues/508.
> Support symbolic range with multiples of block-size as length

- helion/runtime/kernel.py
- test/test_errors.py
Stacked PRs:
* __->__#526
--- --- ---
Fixes #525
> Display error message when too many arguments are passed

- .pre-commit-config.yaml
- lint.sh
- test/test_errors.py
* #533
* __->__#532
* #531
--- --- ---
Upgrade ruff/pyright
> Upgrade ruff/pyright

- helion/_compiler/inductor_lowering.py
- test/test_broadcasting.py
* __->__#533
* #532
* #531
--- --- ---
Allow dynamic fill values in full
Fixes #448
> Allow dynamic fill values in full

- benchmarks/run.py
Stacked PRs:
* #544
* __->__#545
--- --- ---
> Add torch compile to benchmark

- helion/_compiler/dtype_utils.py
- helion/_compiler/inductor_lowering.py
- helion/_compiler/reduction_strategy.py
- helion/language/_tracing_ops.py
- helion/language/matmul_ops.py
- helion/runtime/settings.py
- test/test_associative_scan.expected
- test/test_closures.expected
- test/test_constexpr.expected
- test/test_control_flow.expected
- test/test_dot.expected
- test/test_dot.py
- test/test_examples.expected
- test/test_generate_ast.expected
- test/test_generate_ast.py
- test/test_grid.expected
- test/test_indexing.expected
- test/test_inline_asm_elementwise.expected
- test/test_loops.expected
- test/test_masking.expected
- test/test_matmul.expected
- test/test_misc.expected
- test/test_misc.py
- test/test_persistent_kernels.expected
- test/test_reduce.expected
- test/test_reductions.expected
- test/test_register_tunable.expected
- test/test_specialize.expected
- test/test_tensor_descriptor.expected
- test/test_views.expected
* #543
* __->__#542
--- --- ---
Fix issues with wrong dtypes in generated code
Fixes #512
> Fix issues with wrong dtypes in generated code

- examples/segment_reduction.py
- helion/autotuner/base_search.py
- helion/language/loops.py
- helion/runtime/settings.py
* __->__#543
* #542
--- --- ---
Limit concurrent precompile jobs while autotuning
> Limit concurrent precompile jobs while autotuning

- .github/workflows/benchmark.yml
Stacked PRs:
* __->__#547
--- --- ---
> Add multi selection radio buttons

- .github/workflows/benchmark.yml
Stacked PRs:
* __->__#548
--- --- ---
> Fix benchmark condition

- .github/workflows/benchmark.yml
- .github/workflows/benchmark_dispatch.yml
Stacked PRs:
* __->__#549
--- --- ---
> Move to dispatcher model for benchmarking

- benchmarks/run.py
- examples/jagged_hstu_attn.py
- test/test_examples.expected
- test/test_examples.py
This is to land from the ghstack base to main -- https://github.com/pytorch/helion/pull/527
> Add jagged hstu attention example (i.e. ragged_attention)

- .github/workflows/benchmark.yml
Stacked PRs:
* __->__#556
--- --- ---
> Update test-reports dir

- .github/workflows/benchmark.yml
Stacked PRs:
* __->__#560
* #559
--- --- ---
> Use profiler instead of inductor_benchmarker

- benchmarks/run.py
Stacked PRs:
* #568
* __->__#567
--- --- ---
> [Benchmark] Use custom kernel metric mappings list to accomodate for inconsistent namings

- .github/workflows/benchmark.yml
- benchmarks/run.py
Stacked PRs:
* __->__#568
* #567
--- --- ---
> Add rms norm and cross entropy

- helion/autotuner/base_search.py
* #566
* __->__#565
--- --- ---
Print config for PassManager::run triton errors
> Print config for PassManager::run triton errors

- helion/runtime/kernel.py
Stacked PRs:
* __->__#599
--- --- ---
> Print default config when running with it

- .github/workflows/benchmark.yml
- .github/workflows/test.yml
> Revert "Login to Docker from the workflows"

- benchmarks/run.py
Stacked PRs:
* __->__#609
--- --- ---
> Fix static shape typo

- helion/autotuner/base_search.py
- helion/autotuner/logger.py
- helion/runtime/precompile_shim.py
- test/test_autotuner.py
* __->__#595
--- --- ---
Refactor autotune error handling
> Refactor autotune error handling

- test/test_autotuner.py
* #618
* __->__#617
--- --- ---
Possible fix for CI failures
> Possible fix for CI failures

- helion/autotuner/logger.py
* __->__#618
--- --- ---
Ignore TServiceRouterException errors while autotuning
> Ignore TServiceRouterException errors while autotuning

- .github/workflows/benchmark.yml
Stacked PRs:
* __->__#632
--- --- ---
> Add more kernels to benchmarking

- helion/language/memory_ops.py
- test/test_indexing.py
Stacked PRs:
* #620
* #619
* __->__#621
--- --- ---
> [Ref Mode] Fix hl.store for complex mask pattern

- helion/language/constexpr.py
- test/test_loops.py
* __->__#636
--- --- ---
Make hl.specialize work on sequences
Fixes #622
> Make hl.specialize work on sequences

- helion/exc.py
- helion/language/loops.py
- test/test_errors.py
* __->__#640
--- --- ---
Better error for passing Tile to hl.tile
Fixes #623
> Better error for passing Tile to hl.tile

- examples/int4_gemm.py
`use_default_config=True` was set by accident for this kernel.
> int4_gemm: remove use_default_config=True

- helion/autotuner/base_search.py
- helion/runtime/kernel.py
I believe `static_shapes` settings value also influence the Triton codegen, so I think when we print the config for people to repro the kernel, we should also print the `static_shapes` value for accurate repro.
> Print `static_shapes` settings value along with config for accurate repro

- helion/autotuner/base_search.py
* #696
* #677
* #654
* #697
* #693
* __->__#695
--- --- ---
Run autotune with TRITON_LOCAL_BUILD=1
See https://fb.workplace.com/groups/1223128239223832/permalink/1307844820752173/ for context, this should have no effect outside fbcode.
> Run autotune with TRITON_LOCAL_BUILD=1

- benchmarks/run.py
> Revert "[Benchmark CI] Run rms_norm-bwd and layer_norm-bwd kernels"

- .github/workflows/benchmark.yml
- benchmarks/run.py
> Revert "[Benchmark CI] Add `--list-kernels-for-benchmark-ci` to benchmark runner"

- helion/autotuner/__init__.py
- helion/autotuner/config_fragment.py
- helion/autotuner/pattern_search.py
- helion/runtime/settings.py
- test/test_autotuner.py
* __->__#696
* #677
* #654
--- --- ---
Add PatternSearch autotuning algorithm
> Add PatternSearch autotuning algorithm

- .github/matrix.json
- .github/workflows/benchmark_dispatch.yml
Stacked PRs:
* __->__#720
--- --- ---
> Upgrade rocm CI to 7.0

- .github/matrix.json
- .github/workflows/benchmark_dispatch.yml
Stacked PRs:
* __->__#724
--- --- ---
> [CI] use complete rocm docker images

- .github/workflows/benchmark_dispatch.yml
Signed-off-by: Eli Uriegas <eliuriegas@meta.com>
> ci: Set fail-fast to false

- helion/_compiler/host_function.py
- test/test_misc.py
Stacked PRs:
* __->__#780
--- --- ---
Fixes #752
> Make print output code more robust

- helion/_compiler/host_function.py
- test/test_misc.expected
- test/test_misc.py
Stacked PRs:
* __->__#806
--- --- ---
Fixes #803
> Support 0dim tensor in output code printing

- helion/autotuner/base_search.py
- helion/autotuner/config_generation.py
- helion/autotuner/random_search.py
- helion/runtime/settings.py
- test/test_autotuner.py
* #812
* __->__#814
* #813
--- --- ---
Add autotune_config_overrides
> Add autotune_config_overrides

- helion/autotuner/pattern_search.py
> Reduce initial_population to 100

- .github/matrix.json
Stacked PRs:
* __->__#831
--- --- ---
> Remove py312 vanilla test
